/**
 * ABI Sync — Hardhat Artifacts → UI
 *
 * Reads compiled artifacts and generates hellburn-ui/src/config/abis.js
 * Run after every `npx hardhat compile` when contracts changed.
 *
 * Usage: node scripts/sync-abis.js
 *    or: npx hardhat compile && node scripts/sync-abis.js
 */

const fs = require("fs");
const path = require("path");

// ─── Config ─────────────────────────────────────────────────────
const ARTIFACTS_DIR = path.resolve(__dirname, "../artifacts/contracts");
const OUTPUT_FILE = path.resolve(__dirname, "../../hellburn-ui/src/config/abis.js");

// Contracts to export (filename without .sol → export name for UI)
const CONTRACTS = {
  "HellBurnToken":   "ERC20",
  "GenesisBurn":     "GENESIS",
  "BurnEpochs":      "EPOCHS",
  "HellBurnStaking": "STAKING",
  "BuyAndBurn":      "BUYBURN",
  "MockERC20":       "MOCK_ERC20",
};

// ─── Extract human-readable ABI entries ─────────────────────────
function toHumanReadable(abi) {
  return abi
    .filter((item) => ["function", "event", "error"].includes(item.type))
    .map((item) => {
      if (item.type === "function") {
        const inputs = (item.inputs || []).map((i) => `${i.type} ${i.name}`).join(", ");
        const outputs = (item.outputs || []).map((o) => o.type).join(", ");
        const mutability = item.stateMutability;
        let sig = `function ${item.name}(${inputs})`;
        if (mutability === "view" || mutability === "pure") sig += ` ${mutability}`;
        if (mutability === "payable") sig += " payable";
        if (!["nonpayable", "payable"].includes(mutability) && !sig.includes(mutability)) {
          // already added
        }
        if (outputs) sig += ` returns (${outputs})`;
        return sig;
      }
      if (item.type === "event") {
        const inputs = (item.inputs || [])
          .map((i) => `${i.type}${i.indexed ? " indexed" : ""} ${i.name}`)
          .join(", ");
        return `event ${item.name}(${inputs})`;
      }
      if (item.type === "error") {
        const inputs = (item.inputs || []).map((i) => `${i.type} ${i.name}`).join(", ");
        return `error ${item.name}(${inputs})`;
      }
      return null;
    })
    .filter(Boolean);
}

// ─── Find artifact JSON ─────────────────────────────────────────
function findArtifact(contractName) {
  // Hardhat artifacts: contracts/<Name>.sol/<Name>.json
  // or for mocks: contracts/mocks/<Name>.sol/<Name>.json
  const candidates = [
    path.join(ARTIFACTS_DIR, `${contractName}.sol`, `${contractName}.json`),
    path.join(ARTIFACTS_DIR, "mocks", `${contractName}.sol`, `${contractName}.json`),
    path.join(ARTIFACTS_DIR, "interfaces", `I${contractName}.sol`, `I${contractName}.json`),
  ];
  for (const p of candidates) {
    if (fs.existsSync(p)) return p;
  }
  return null;
}

// ─── Main ───────────────────────────────────────────────────────
function main() {
  console.log("🔥 ABI Sync — Hardhat → hellburn-ui\n");

  const exports = {};
  let found = 0;
  let missing = 0;

  for (const [contractName, exportName] of Object.entries(CONTRACTS)) {
    const artifactPath = findArtifact(contractName);
    if (!artifactPath) {
      console.log(`  ❌ ${contractName} — artifact not found (compile first?)`);
      missing++;
      continue;
    }

    const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf-8"));
    const humanAbi = toHumanReadable(artifact.abi);
    exports[exportName] = humanAbi;
    found++;
    console.log(`  ✅ ${contractName} — ${humanAbi.length} entries`);
  }

  if (found === 0) {
    console.log("\n  ⚠️  No artifacts found. Run `npx hardhat compile` first.");
    process.exit(1);
  }

  // ─── Generate output file ───────────────────────────────────
  let output = `/**\n * Auto-generated by sync-abis.js — DO NOT EDIT MANUALLY\n * Generated: ${new Date().toISOString()}\n */\n\n`;

  for (const [name, abi] of Object.entries(exports)) {
    output += `export const ${name}_ABI = [\n`;
    for (const entry of abi) {
      output += `  "${entry}",\n`;
    }
    output += `];\n\n`;
  }

  // Ensure output directory exists
  const outputDir = path.dirname(OUTPUT_FILE);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  fs.writeFileSync(OUTPUT_FILE, output);

  console.log(`\n  📄 Written to: ${OUTPUT_FILE}`);
  console.log(`  📊 ${found} contracts synced${missing > 0 ? `, ${missing} missing` : ""}`);
  console.log("\n  Done! UI ABIs are up to date. ✅");
}

main();
